## Register New User

POST http://localhost:8081/auth/register
Content-Type: application/json

{
    "firstName": "John7",
    "lastName": "Doe",
    "username": "john_doe7",
    "email": "john.doe7@example.com",
    "password": "Password123!"
}